# Generated by Django 4.0.2 on 2022-02-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_interest_board_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='create_date',
            new_name='pub_date',
        ),
    ]
